# Generated by Django 4.2.7 on 2024-02-25 08:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_role_user_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="role",
            new_name="roles",
        ),
    ]
