# Generated by Django 4.2.7 on 2024-02-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_category_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(related_name="products", to="shop.image"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
