# Generated by Django 4.2.7 on 2024-02-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_product_images_alter_product_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="products", to="shop.image"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=12),
        ),
    ]
